
version: '3.2'

services:
  api:
    build: .
    ports:
      - 7001:5000
    environment:
      - DEBUG=1
      - FLASK_APP=run.py 
    depends_on:
      - db
  db:
    image: mysql:5
    restart: always
    environment: 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
      - MYSQL_DATABASE=students
    ports: 
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated

volumes:
  mysql-data: